import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import { satoshi, clashDisplay } from "./fonts";
import "./globals.css";
import Navbar from "./components/home/Navbar";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins-var",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", satoshi.variable, clashDisplay.variable, poppins.variable, "font-sans", geist.variable)}
    >
      <body className="h-full min-h-full w-ful ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
